<a href="https://colab.research.google.com/github/DiyaShah2753/ML/blob/main/lab1_ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
x = 5
print(x,"Type:",type(x))
x = "Hello"
print(x,"Type:",type(x))
x = [1,2,3]
print(x,"Type:",type(x))


alist = [1, 2, 3, 4, 5]
narray = np.array([1,2,3,4])
print(alist)
print(narray)
print(type(alist))
print(type(narray))

narray1 = np.array([1, 2, 3])
print(narray + narray)
print(alist + alist)

#print(narray + narray1)
print(alist + alist)

alist1 = [1, 2, 3, 4]

print(alist + alist1)

print(narray * 3)
print(alist * 3)

x = np.array([[1,2],[3,4]],dtype = np.float64)
y = np.array([[5,6],[7,8]],dtype = np.float64)

print(x+y)
print(np.add(x,y))

print(x - y)
print(np.subtract(x, y))

print(x * y)
print(np.multiply(x, y))

print(x.dot(y))


print(x/y)
print(np.divide(x,y))

5 Type: <class 'int'>
Hello Type: <class 'str'>
[1, 2, 3] Type: <class 'list'>
[1, 2, 3, 4, 5]
[1 2 3 4]
<class 'list'>
<class 'numpy.ndarray'>
[2 4 6 8]
[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[1, 2, 3, 4, 5, 1, 2, 3, 4]
[ 3  6  9 12]
[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]
[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]
[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]
[[19. 22.]
 [43. 50.]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [ ]:
print(np.sqrt(x))


x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11, 12])
print(v.dot(w))
print(np.dot(v, w))

print(v @ w)

print(x.dot(v))
print(np.dot(x, v))
print(x @ v)

[[1.         1.41421356]
 [1.73205081 2.        ]]
219
219
219
[29 67]
[29 67]
[29 67]


In [ ]:
x = np.array([[1,2],[3,4]])
print(np.sum(x))
print(np.sum(x , axis=0))
print(np.sum(x , axis=1))

10
[4 6]
[3 7]


In [ ]:
print(x)
print("Transpose\n",x.T)

v = np.array([[1,2,3]])

print(v )
print("transpose\n", v.T)

[[1 2]
 [3 4]]
Transpose
 [[1 3]
 [2 4]]
[[1 2 3]]
transpose
 [[1]
 [2]
 [3]]


In [ ]:
npmatrix1 = np.array([narray, narray, narray])
npmatrix2 = np.array([alist, alist, alist])
npmatrix3 = np.array([narray, [1, 1, 1, 1], narray])
print(npmatrix1)
print(npmatrix2)
print(npmatrix3)

[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]
[[1 2 3 4 5]
 [1 2 3 4 5]
 [1 2 3 4 5]]
[[1 2 3 4]
 [1 1 1 1]
 [1 2 3 4]]


In [ ]:
okmatrix = np.array([[1,2],[3,4]])
print(okmatrix)

print(okmatrix * 2)



badmatrix = np.array([[1,2 ], [3, 4], [6,7, 8]], dtype=object) 
print(badmatrix)
print(badmatrix * 2)


print(okmatrix)
result = okmatrix * 2 + 1 
print(result)

result1 = okmatrix + okmatrix
print(result1)


result1 = okmatrix - okmatrix
print(result1)

result = okmatrix * okmatrix
print(result)

[[1 2]
 [3 4]]
[[2 4]
 [6 8]]
[list([1, 2]) list([3, 4]) list([6, 7, 8])]
[list([1, 2, 1, 2]) list([3, 4, 3, 4]) list([6, 7, 8, 6, 7, 8])]
[[1 2]
 [3 4]]
[[3 5]
 [7 9]]
[[2 4]
 [6 8]]
[[0 0]
 [0 0]]


In [ ]:
matrixmn = np.array([[1,2],[3,4],[5,6]])
print('matrixmn 3 x 2')
print(matrixmn)
print('matrixmnTranspose 2 x 3')
print(matrixmn.T)


nparray = np.array([1, 2, 3, 4]) 
print('Original array')
print(nparray)
print('Transposed array')
print(nparray.T)


nparray = np.array([[1, 2, 3, 4]]) 
print('Original array')
print(nparray)
print('Transposed array')
print(nparray.T)


matrixmn 3 x 2
[[1 2]
 [3 4]
 [5 6]]
matrixmnTranspose 2 x 3
[[1 3 5]
 [2 4 6]]
Original array
[1 2 3 4]
Transposed array
[1 2 3 4]
Original array
[[1 2 3 4]]
Transposed array
[[1]
 [2]
 [3]
 [4]]


In [ ]:
narray = np.array([1,2,3,4])
norm1 = np.linalg.norm(narray)
print(norm1)

narray = np.array([[1,2],[3,4]])
norm1 = np.linalg.norm(narray)
print(norm1)


nparray2 = np.array([[1, 1], [2, 2], [3, 3]])
normByCols = np.linalg.norm(nparray2, axis=0) 
normByRows = np.linalg.norm(nparray2, axis=1)
print(normByCols)
print(normByRows)

5.477225575051661
5.477225575051661
[3.74165739 3.74165739]
[1.41421356 2.82842712 4.24264069]


In [ ]:
narray = np.array([0,1,2,3])
narray2 = np.array([4, 5, 6, 7])

result = np.dot(narray,narray2)
print(result)

result1 = np.sum(narray * narray2)
print(result1)

result1 = narray @ narray2
print(result1)


flavor4 = 0
for a, b in zip(narray, nparray2):
  flavor4 += a * b
print(flavor4)

38
38
38
38


In [ ]:
norm1 = np.dot([1,2],[3,4])
#norm1 = np.dot(np.array([1, 2]), np.array([3, 4]))
norm2 = np.dot(np.array([1,2]),np.array([3,4]))
print(norm1)
print(norm2) 
print(norm1, '=', norm2 )

11
11
11 = 11
