<a href="https://colab.research.google.com/github/DiyaShah2753/ML/blob/main/ML_Lab3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from sklearn import preprocessing
from sklearn.naive_bayes import GaussianNB, MultinomialNB

# Dataset
weather = ['Sunny', 'Sunny', 'Overcast', 'Rainy', 'Rainy','Rainy', 'Overcast','Sunny', 'Sunny', 'Rainy', 'Sunny', 'Overcast', 'Overcast', 'Rainy']
temp = ['Hot','Hot','Hot','Mild','Cool','Cool','Cool','Mild','Cool','Mild','Mild','Mild','Hot','Mild']
play=['No','No','Yes','Yes','Yes','No','Yes','No','Yes','Yes','Yes','Yes','Yes','No']

# label encoder
le = preprocessing.LabelEncoder()

# convert string labels into numbers
weather_encoded = le.fit_transform(weather)
print("Weather: ", weather_encoded);

temp_encoded=le.fit_transform(temp)
label=le.fit_transform(play)
print("Temp:",temp_encoded)
print("Play:",label)

Weather:  [2 2 0 1 1 1 0 2 2 1 2 0 0 1]
Temp: [1 1 1 2 0 0 0 2 0 2 2 2 1 2]
Play: [0 0 1 1 1 0 1 0 1 1 1 1 1 0]


In [ ]:
# mearge different features to prepare dataset

features = tuple(zip(weather_encoded, temp_encoded))
print(features)

((2, 1), (2, 1), (0, 1), (1, 2), (1, 0), (1, 0), (0, 0), (2, 2), (2, 0), (1, 2), (2, 2), (0, 2), (0, 1), (1, 2))


In [ ]:
# Traning
model = MultinomialNB()
model.fit(features, label)

# Predict Output
predicted = model.predict([[0,2]])
print("Predicted Value: ", predicted)

Predicted Value:  [1]


In [ ]:
predicted = model.predict([[0,1]])
print("Predicted Value: ", predicted)

Predicted Value:  [1]


In [ ]:
print(model.predict_proba([[0,2]]))
print(model.predict_proba([[0,1]]))

[[0.24084427 0.75915573]]
[[0.29568697 0.70431303]]


# Exercise: Manually calculate output for the following cases and compare it with system’s output.
##(1) Will you play if the temperature is ‘Hot’ and weather is ‘overcast’?
##(2) Will you play if the temperature is ‘Mild’ and weather is ‘Sunny’?

In [ ]:
predicted = model.predict([[0,1]])
manual = 1
print("Predicted= ",predicted,"\nManual= ",manual,"\nPredicted = Manual? ",predicted[0]==manual)

Predicted=  [1] 
Manual=  1 
Predicted = Manual?  True


In [ ]:
predicted = model.predict([[2,2]])
manual = 1
print("Predicted= ",predicted,"\nManual= ",manual,"\nPredicted = Manual? ",predicted[0]==manual)

Predicted=  [1] 
Manual=  1 
Predicted = Manual?  True


#For Iris Data set (pdf2)


In [ ]:
import numpy as np
from sklearn import datasets
from sklearn.naive_bayes import GaussianNB

# Load dataset
iris = datasets.load_iris()

In [ ]:
print("Features: ", iris.feature_names)
print("\nLabels: ", iris.target_names)
print("\nData shape: ",iris.data.shape)
print("\nTraget shape: ",iris.target.shape)

print("\nData type: ",type(iris.data))
newdata = iris.data[50:,:]
newtarget = iris.target[50:]

# print data(feature)shape
print("\nNew Data shape: ",newdata.shape)

#print data(target)shape
print("\nNew Traget shape: ",newtarget.shape)

Features:  ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']

Labels:  ['setosa' 'versicolor' 'virginica']

Data shape:  (150, 4)

Traget shape:  (150,)

Data type:  <class 'numpy.ndarray'>

New Data shape:  (100, 4)

New Traget shape:  (100,)


In [ ]:
from sklearn.model_selection import train_test_split

data_train, data_test, target_train, target_test = train_test_split(newdata, newtarget, test_size=0.30, random_state=5)

gnb = GaussianNB()
gnb.fit(data_train, target_train)
target_pred = gnb.predict(data_test)

In [ ]:
from sklearn import metrics

# print("Accuracy: ", metrics.acuracy_score(target_test, target_pred))
print("Accuracy:",metrics.accuracy_score(target_test, target_pred))

Accuracy: 0.9


In [ ]:
from sklearn.metrics import confusion_matrix
confusion_matrix(target_test, target_pred)

array([[16,  1],
       [ 2, 11]])

In [ ]:
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score

precision = precision_score(target_test, target_pred)
recall = recall_score(target_test, target_pred)
print('Precision: {}'. format(precision))
print('recall : {}'.format(recall))

Precision: 0.8888888888888888
recall : 0.9411764705882353


#Iris dataset (pdf3)

In [ ]:
from sklearn import datasets
from sklearn.naive_bayes import GaussianNB

iris = datasets.load_iris()

print("Features: ", iris.feature_names)

print("Labels: ", iris.target_names)

iris.data.shape

Features:  ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
Labels:  ['setosa' 'versicolor' 'virginica']


(150, 4)

In [ ]:
# from sklearn.model_selection import train_test_split
data_train, data_test, target_train, target_test = train_test_split(iris.data,iris.target, test_size = 0.30, random_state = 10)

import numpy as np
gnb = GaussianNB()
gnb.fit(data_train, target_train)
target_pred = gnb.predict(data_test)

In [ ]:
from sklearn import metrics
print("Accuracy: ", metrics.accuracy_score(target_test, target_pred))

Accuracy:  1.0


In [ ]:
from sklearn.metrics import confusion_matrix
confusion_matrix(target_test, target_pred)

array([[14,  0,  0],
       [ 0, 17,  0],
       [ 0,  0, 14]])

In [ ]:
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score

precision = precision_score(target_test, target_pred, average=None)
recall = recall_score(target_test, target_pred, average=None)

print('precision: {}'.format(precision))
print('recall: {}'.format(recall))

precision: [1. 1. 1.]
recall: [1. 1. 1.]


#Exercise

##Try the algo on Dataset2 - OneHotEncoding of features: and Train test Division 75%-25%

In [ ]:
from sklearn import datasets
import pandas as pd
import numpy as np
from sklearn.naive_bayes import GaussianNB
import sklearn.preprocessing as preprocessing

data = pd.read_csv('Dataset2.csv')
print(data)

outlook_encoded = pd.get_dummies(data.Outlook)
temperature_encoded = pd.get_dummies(data.Temp)
wind_encoded = pd.get_dummies(data.Wind)
humidity_encoded = pd.get_dummies(data.Humidity)
# outlook_encoded
# temperature_encoded
# wind_encoded
# humidity_encoded

# x = data.iloc[:,:1].values
# x[:,0] = outlook_encoded
# x[:,1] = temperature_encoded
# x[:,2] = wind_encoded
# x[:,3] = humidity_encoded
# print(x)

# y = data.iloc[:,-1].values
# y = labelEnc.fit_transform(y)
# onehotEnc.fit(y.reshape(-1, 1))
# print(y)

   Outlook Temp Wind Humidity Class
0        R    H    F   Normal     N
1        R    H    T     High     N
2        O    H    F   Normal     Y
3        S    M    F   Normal     N
4        S    M    F   Normal     Y
5        S    M    T      Low     Y
6        O    C    T   Normal     Y
7        R    C    F   Normal     Y
8        R    C    F      Low     Y
9        S    M    F     High     Y
10       R    M    T     High     Y
11       O    M    T      Low     Y
12       O    H    F   Normal     Y
13       S    M    T   Normal     N


In [ ]:
x = pd.concat([outlook_encoded, temperature_encoded, wind_encoded,humidity_encoded],axis='columns')
x

O  R  S  C  H  M  F  T  High  Low  Normal
0   0  1  0  0  1  0  1  0     0    0       1
1   0  1  0  0  1  0  0  1     1    0       0
2   1  0  0  0  1  0  1  0     0    0       1
3   0  0  1  0  0  1  1  0     0    0       1
4   0  0  1  0  0  1  1  0     0    0       1
5   0  0  1  0  0  1  0  1     0    1       0
6   1  0  0  1  0  0  0  1     0    0       1
7   0  1  0  1  0  0  1  0     0    0       1
8   0  1  0  1  0  0  1  0     0    1       0
9   0  0  1  0  0  1  1  0     1    0       0
10  0  1  0  0  0  1  0  1     1    0       0
11  1  0  0  0  0  1  0  1     0    1       0
12  1  0  0  0  1  0  1  0     0    0       1
13  0  0  1  0  0  1  0  1     0    0       1

In [ ]:
y = data.Class
y

0     N
1     N
2     Y
3     N
4     Y
5     Y
6     Y
7     Y
8     Y
9     Y
10    Y
11    Y
12    Y
13    N
Name: Class, dtype: object

In [ ]:
from sklearn.model_selection import train_test_split
data_train, data_test, target_train, target_test = train_test_split(x,y, train_size = 0.75, random_state = 81)

In [ ]:
import numpy as np
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()

gnb.fit(data_train, target_train)

target_pred = gnb.predict(data_test)

In [ ]:
from sklearn import metrics

print("Accuracy:",metrics.accuracy_score(target_test, target_pred))
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score

precision = precision_score(target_test, target_pred, average=None)
recall = recall_score(target_test, target_pred, average=None)

print('precision: {}'.format(precision))
print('recall: {}'.format(recall))

Accuracy: 0.75
precision: [0.5 1. ]
recall: [1.         0.66666667]


In [ ]:
target_pred = gnb.predict([[0,1,0,0,0,1,1,0,0,0,1], [0,0,1,1,0,0,0,1,1,0,0]])
print(target_pred)

['N' 'Y']


/usr/local/lib/python3.8/dist-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but GaussianNB was fitted with feature names
  warnings.warn(


In [ ]:
print(gnb.predict_proba([[0,1,0,0,0,1,1,0,0,0,1]]))
# print(gnb.predict([[1,2,2,0]]))
print(gnb.predict_proba([[0,0,1,1,0,0,0,1,1,0,0]]))

[[1.0000000e+00 1.0858069e-13]]
[[0. 1.]]


/usr/local/lib/python3.8/dist-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but GaussianNB was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but GaussianNB was fitted with feature names
  warnings.warn(


##Apply algorithm on wine dataset - LabelEncoding of features: and Train test Division 80%-20%

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.naive_bayes import GaussianNB
from sklearn import preprocessing
from sklearn.metrics import confusion_matrix
from sklearn.preprocessing import LabelEncoder
import pandas as pd
from sklearn import datasets

wine = datasets.load_wine()
le = preprocessing.LabelEncoder()

from sklearn.model_selection import train_test_split

# using random state as last 2 digits of my Roll No
data_train, data_test, target_train, target_test = train_test_split(wine.data,wine.target,train_size=0.8,test_size=0.2, random_state=81)

In [ ]:
import numpy as np
gnb = GaussianNB()

gnb.fit(data_train, target_train)

target_pred = gnb.predict(data_test)

In [ ]:
print("Accuracy:",metrics.accuracy_score(target_test, target_pred))

Accuracy: 1.0


In [ ]:
from sklearn.metrics import confusion_matrix
confusion_matrix(target_test, target_pred)

array([[14,  0,  0],
       [ 0, 11,  0],
       [ 0,  0, 11]])

In [ ]:
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
precision = precision_score(target_test, target_pred, average=None)
recall = recall_score(target_test, target_pred, average=None)
print('precision: {}'.format(precision))
print('recall: {}'.format(recall))

precision: [1. 1. 1.]
recall: [1. 1. 1.]
